### ISSUE TITLE
Reopening issues/more events

### ISSUE THREAD

**Issue by MiningPickaxe** [jellysquid3/gitlab-discord-bot#6]
Firstoff, a really great bridge you created there. Was a bit hard to set up, I had to use --strict_mode to execute the app.js successfully (maybe add that to your readme in the section "troubleshooting")
When I reopen an issue, it posts a message in discord looking like this: http://prnt.sc/e4eqql would be cool, if you could fix the "???" to show "reopened". When I get the time, I could try to fork your repository, but I'm not really good in the javascript-department.
Also getting notified when someone created a new wiki page would be cool as well as build events (at least it looks like it is not supported yet)
Thanks for your good work!

**Comment by jellysquid3** [comment]
The bridge should launch without any extra CLI arguments unless you're using an old version of NodeJS (I'm currently using Node v7.5.0, the latest).

As for the re-opening issue, it seems I blindly thought GitLab would just send an `opened` event rather than `reopened`. I should have it fixed very shortly.

**Comment by MiningPickaxe** [comment]
Oh, I'm still using node.js 4.7.3 because of compatability issues... That could be the problem. But it works nevertheless! Just need to launch it with an argument
